const DEFAULT_GROWTH = { hp: [5, 8], mp: 0, atk: 2, pDef: 1, mDef: 1, agi: 1 };

const startingMembers = [
  { name: "アルス", job: "勇者", attackType: "both", positionType: "前衛", range: 1, level: 1, hp: 34, maxHp: 34, mp: 10, maxMp: 10, atk: 8, pDef: 4, mDef: 4, agi: 8, policy: 3, growth: { hp: [5, 7], mp: 0, atk: 2, pDef: 1, mDef: 1, agi: [0, 1] }, exp: 0, weaponBase: "剣", armorBase: "鎧", weaponGrade: 0, armorGrade: 0, weapon: "革の剣", armor: "革の鎧", weaponAtk: 0, armorDef: 0 },
  { name: "ガロン", job: "戦士", attackType: "physical", positionType: "前衛", range: 1, level: 1, hp: 42, maxHp: 42, mp: 10, maxMp: 10, atk: 10, pDef: 7, mDef: 4, agi: 5, policy: 1, growth: { hp: [7, 10], mp: 0, atk: 3, pDef: 2, mDef: 1, agi: 0 }, exp: 0, weaponBase: "斧", armorBase: "鎧", weaponGrade: 0, armorGrade: 0, weapon: "革の斧", armor: "革の鎧", weaponAtk: 0, armorDef: 0 }
];

const recruitableMembers = [
  { name: "ミリア", job: "僧侶", recruitCost: 4, attackType: "magic", positionType: "後衛", range: 2, level: 1, hp: 28, maxHp: 28, mp: 6, maxMp: 6, atk: 5, pDef: 2, mDef: 5, agi: 6, policy: 4, growth: { hp: [4, 6], mp: 0, atk: 1, pDef: 1, mDef: 3, agi: 1 }, exp: 0, weaponBase: "杖", armorBase: "ローブ", weaponGrade: 0, armorGrade: 0, weapon: "革の杖", armor: "革のローブ", weaponAtk: 0, armorDef: 0, joinFloor: 8 },
  { name: "スプーン", job: "魔法使い", recruitCost: 8, attackType: "magic", spellName: "フレイム", spellPattern: "row", positionType: "後衛", range: 3, level: 1, hp: 24, maxHp: 24, mp: 6, maxMp: 6, atk: 8, pDef: 1, mDef: 5, agi: 7, policy: 5, growth: { hp: [2, 3], mp: 0, atk: 3, pDef: 0, mDef: 3, agi: 1 }, exp: 0, weaponBase: "杖", armorBase: "ローブ", weaponGrade: 0, armorGrade: 0, weapon: "革の杖", armor: "革のローブ", weaponAtk: 0, armorDef: 0, joinFloor: 16 },
  { name: "ノルン", job: "騎士", recruitCost: 6, attackType: "physical", normalAttackPattern: "pierce-column", positionType: "両方", range: 2, level: 1, hp: 38, maxHp: 38, mp: 6, maxMp: 6, atk: 9, pDef: 8, mDef: 3, agi: 4, policy: 2, growth: { hp: [6, 9], mp: 0, atk: 2, pDef: 3, mDef: 1, agi: 0 }, exp: 0, weaponBase: "槍", armorBase: "鎧", weaponGrade: 0, armorGrade: 0, weapon: "革の槍", armor: "革の鎧", weaponAtk: 0, armorDef: 0, joinFloor: 32 }
];

const tavernExpansionMembers = [
  { name: "エルマ", job: "僧侶", recruitCost: 14, attackType: "magic", positionType: "後衛", range: 2, level: 1, hp: 30, maxHp: 30, mp: 7, maxMp: 7, atk: 6, pDef: 3, mDef: 6, agi: 5, policy: 3, growth: { hp: [4, 6], mp: 0, atk: 2, pDef: 1, mDef: 3, agi: 1 }, exp: 0, weaponBase: "杖", armorBase: "ローブ", weaponGrade: 0, armorGrade: 0, weapon: "革の杖", armor: "革のローブ", weaponAtk: 0, armorDef: 0 },
  { name: "ダブチ", job: "戦士", recruitCost: 15, attackType: "physical", positionType: "前衛", range: 1, level: 1, hp: 46, maxHp: 46, mp: 6, maxMp: 6, atk: 11, pDef: 7, mDef: 3, agi: 4, policy: 1, growth: { hp: [8, 15], mp: 0, atk: 3, pDef: 2, mDef: 1, agi: 0 }, exp: 0, weaponBase: "斧", armorBase: "鎧", weaponGrade: 0, armorGrade: 0, weapon: "革の斧", armor: "革の鎧", weaponAtk: 0, armorDef: 0 },
  { name: "メモリ", job: "魔法使い", recruitCost: 19, attackType: "magic", spellName: "ファイア", spellPattern: "pierce-column", positionType: "後衛", range: 3, level: 1, hp: 26, maxHp: 26, mp: 8, maxMp: 8, atk: 9, pDef: 1, mDef: 6, agi: 8, policy: 4, growth: { hp: [2, 4], mp: 0, atk: 4, pDef: 0, mDef: 22, agi: 1 }, exp: 0, weaponBase: "杖", armorBase: "ローブ", weaponGrade: 0, armorGrade: 0, weapon: "革の杖", armor: "革のローブ", weaponAtk: 0, armorDef: 0 },
  { name: "ピッポ", job: "騎士", recruitCost: 16, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 40, maxHp: 40, mp: 6, maxMp: 6, atk: 8, pDef: 11, mDef: 4, agi: 3, policy: 2, growth: { hp: [20, 22], mp: 0, atk: 2, pDef: 7, mDef: 1, agi: 0 }, exp: 0, weaponBase: "槍", armorBase: "鎧", weaponGrade: 0, armorGrade: 0, weapon: "革の槍", armor: "革の鎧", weaponAtk: 0, armorDef: 0 },
  { name: "カリン", job: "勇者", recruitCost: 16, attackType: "both", positionType: "前衛", range: 1, level: 1, hp: 33, maxHp: 33, mp: 9, maxMp: 9, atk: 8, pDef: 4, mDef: 4, agi: 9, policy: 3, growth: { hp: [5, 7], mp: 0, atk: 4, pDef: 2, mDef: 2, agi: [0, 1] }, exp: 0, weaponBase: "剣", armorBase: "鎧", weaponGrade: 0, armorGrade: 0, weapon: "革の剣", armor: "革の鎧", weaponAtk: 0, armorDef: 0 }
];

const tavernSecondExpansionMembers = [
  { name: "セラ", job: "僧侶", recruitCost: 30, attackType: "magic", positionType: "後衛", range: 2, level: 1, hp: 34, maxHp: 34, mp: 9, maxMp: 9, atk: 8, pDef: 4, mDef: 8, agi: 6, policy: 3, growth: { hp: [5, 7], mp: 0, atk: 2, pDef: 2, mDef: 4, agi: 1 }, exp: 0, weaponBase: "杖", armorBase: "ローブ", weaponGrade: 0, armorGrade: 0, weapon: "革の杖", armor: "革のローブ", weaponAtk: 0, armorDef: 0 },
  { name: "バルド", job: "戦士", recruitCost: 32, attackType: "physical", positionType: "前衛", range: 1, level: 1, hp: 56, maxHp: 56, mp: 13, maxMp: 13, atk: 14, pDef: 9, mDef: 4, agi: 5, policy: 1, growth: { hp: [8, 24], mp: 0, atk: 5, pDef: 3, mDef: 1, agi: 1 }, exp: 0, weaponBase: "斧", armorBase: "鎧", weaponGrade: 0, armorGrade: 0, weapon: "革の斧", armor: "革の鎧", weaponAtk: 0, armorDef: 0 },
  { name: "ルキア", job: "魔法使い", recruitCost: 36, attackType: "magic", spellName: "メティオ", spellPattern: "all", positionType: "後衛", range: 3, level: 1, hp: 30, maxHp: 30, mp: 10, maxMp: 10, atk: 11, pDef: 2, mDef: 8, agi: 9, policy: 4, growth: { hp: [2, 6], mp: 0, atk: 6, pDef: 1, mDef: 10, agi: 1 }, exp: 0, weaponBase: "杖", armorBase: "ローブ", weaponGrade: 0, armorGrade: 0, weapon: "革の杖", armor: "革のローブ", weaponAtk: 0, armorDef: 0 },
  { name: "オルド", job: "騎士", recruitCost: 34, attackType: "physical", normalAttackPattern: "pierce-column",  positionType: "両方", range: 2, level: 1, hp: 48, maxHp: 48, mp: 8, maxMp: 8, atk: 11, pDef: 32, mDef: 5, agi: 4, policy: 2, growth: { hp: [27, 30], mp: 0, atk: 3, pDef: 14, mDef: 2, agi: 2 }, exp: 0, weaponBase: "槍", armorBase: "鎧", weaponGrade: 0, armorGrade: 0, weapon: "革の槍", armor: "革の鎧", weaponAtk: 0, armorDef: 0 },
  { name: "ファルナ", job: "勇者", recruitCost: 100, attackType: "both", positionType: "両方", range: 2, level: 1, hp: 40, maxHp: 40, mp: 11, maxMp: 11, atk: 11, pDef: 6, mDef: 6, agi: 10, policy: 3, growth: { hp: [13, 14], mp: 0, atk: 5, pDef: 3, mDef: 3, agi: [1, 2] }, exp: 0, weaponBase: "剣", armorBase: "鎧", weaponGrade: 0, armorGrade: 0, weapon: "革の剣", armor: "革の鎧", weaponAtk: 0, armorDef: 0 }
];

const hunterGuildMembers = [
  { name: "ヒビノ", job: "狩人", recruitCost: 15, attackType: "physical", positionType: "後衛", range: 3, level: 1, hp: 29, maxHp: 29, mp: 6, maxMp: 6, atk: 9, pDef: 3, mDef: 3, agi: 10, policy: 2, growth: { hp: [4, 6], mp: 0, atk: 2, pDef: 1, mDef: 1, agi: 2 }, exp: 0, weaponBase: "弓", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の弓", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 1 },
  { name: "ミナト", job: "罠師", recruitCost: 28, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 30, maxHp: 30, mp: 6, maxMp: 6, atk: 8, pDef: 3, mDef: 3, agi: 11, policy: 3, growth: { hp: [4, 6], mp: 0, atk: 2, pDef: 1, mDef: 1, agi: 2 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 2 },
  { name: "クロエ", job: "罠師", recruitCost: 32, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 31, maxHp: 31, mp: 7, maxMp: 7, atk: 9, pDef: 3, mDef: 3, agi: 12, policy: 3, growth: { hp: [4, 6], mp: 0, atk: 2, pDef: 1, mDef: 1, agi: 3 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 3 },
  { name: "キリカ", job: "狩人", recruitCost: 15, attackType: "physical", positionType: "後衛", range: 3, level: 1, hp: 31, maxHp: 31, mp: 6, maxMp: 6, atk: 10, pDef: 3, mDef: 3, agi: 11, policy: 2, growth: { hp: [4, 6], mp: 0, atk: 3, pDef: 1, mDef: 1, agi: 2 }, exp: 0, weaponBase: "弓", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の弓", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 4 },
  { name: "バルク", job: "罠師", recruitCost: 54, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 35, maxHp: 35, mp: 7, maxMp: 7, atk: 11, pDef: 4, mDef: 3, agi: 13, policy: 4, growth: { hp: [5, 7], mp: 0, atk: 3, pDef: 1, mDef: 1, agi: 3 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 6 },
  { name: "ロビン", job: "狩人", recruitCost: 46, attackType: "physical", normalAttackPattern: "pierce-column",  positionType: "後衛", range: 3, level: 1, hp: 33, maxHp: 33, mp: 7, maxMp: 7, atk: 11, pDef: 4, mDef: 3, agi: 12, policy: 3, growth: { hp: [5, 7], mp: 0, atk: 5, pDef: 1, mDef: 1, agi: 2 }, exp: 0, weaponBase: "弓", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の弓", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 7 },
  { name: "ナギ", job: "罠師", recruitCost: 94, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 38, maxHp: 38, mp: 8, maxMp: 8, atk: 12, pDef: 4, mDef: 4, agi: 15, policy: 4, growth: { hp: [9, 10], mp: 0, atk: 5, pDef: 1, mDef: 1, agi: 4 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 9 },
  { name: "シルヴァ", job: "狩人", recruitCost: 66, attackType: "physical", normalAttackPattern: "pierce-column",  positionType: "後衛", range: 3, level: 1, hp: 35, maxHp: 35, mp: 7, maxMp: 7, atk: 12, pDef: 4, mDef: 4, agi: 13, policy: 3, growth: { hp: [7, 9], mp: 0, atk: 5, pDef: 1, mDef: 1, agi: 5 }, exp: 0, weaponBase: "弓", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の弓", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 10 }
];

const thiefGuildMembers = [
  { name: "イモス", job: "盗賊", recruitCost: 5, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 30, maxHp: 30, mp: 7, maxMp: 7, atk: 7, pDef: 3, mDef: 2, agi: 12, policy: 2, growth: { hp: [4, 6], mp: 0, atk: 2, pDef: 1, mDef: 1, agi: 5 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, joinFloor: 24, guildLevel: 1 },
  { name: "オサフン", job: "忍者", recruitCost: 40, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 29, maxHp: 29, mp: 7, maxMp: 7, atk: 8, pDef: 2, mDef: 3, agi: 14, policy: 2, growth: { hp: [3, 5], mp: 0, atk: 3, pDef: 1, mDef: 1, agi: 7 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 2 },
  { name: "スズネ", job: "忍者", recruitCost: 44, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 31, maxHp: 31, mp: 8, maxMp: 8, atk: 9, pDef: 2, mDef: 3, agi: 15, policy: 2, growth: { hp: [3, 5], mp: 0, atk: 4, pDef: 1, mDef: 1, agi: 7 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 3 },
  { name: "フィオナ", job: "盗賊", recruitCost: 15, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 32, maxHp: 32, mp: 8, maxMp: 8, atk: 8, pDef: 3, mDef: 3, agi: 13, policy: 2, growth: { hp: [4, 6], mp: 0, atk: 3, pDef: 2, mDef: 1, agi: 6 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 4 },
  { name: "ハヤテ", job: "忍者", recruitCost: 104, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 36, maxHp: 36, mp: 9, maxMp: 9, atk: 11, pDef: 3, mDef: 3, agi: 16, policy: 2, growth: { hp: [5, 7], mp: 0, atk: 4, pDef: 1, mDef: 1, agi: 8 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 6 },
  { name: "レナ", job: "盗賊", recruitCost: 25, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 40, maxHp: 40, mp: 9, maxMp: 9, atk: 12, pDef: 3, mDef: 2, agi: 12, policy: 2, growth: { hp: [6, 8], mp: 0, atk: 4, pDef: 3, mDef: 1, agi: 6 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 7 },
  { name: "シグレ", job: "忍者", recruitCost: 104, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 42, maxHp: 42, mp: 10, maxMp: 10, atk: 13, pDef: 3, mDef: 4, agi: 18, policy: 2, growth: { hp: [6, 8], mp: 0, atk: 5, pDef: 1, mDef: 1, agi: 9 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 9 },
  { name: "ジーク", job: "盗賊", recruitCost: 35, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 52, maxHp: 52, mp: 10, maxMp: 10, atk: 13, pDef: 3, mDef: 2, agi: 13, policy: 2, growth: { hp: [8, 10], mp: 0, atk: 6, pDef: 1, mDef: 1, agi: 7 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 10 },
];

const merchantGuildMembers = [
  { name: "マルコ", job: "商人", recruitCost: 18, attackType: "physical", positionType: "前衛", range: 2, level: 1, hp: 28, maxHp: 28, mp: 6, maxMp: 6, atk: 6, pDef: 3, mDef: 4, agi: 7, policy: 9, growth: { hp: [12, 24], mp: 0, atk: 1, pDef: 1, mDef: 1, agi: 0 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 1 },
  { name: "アート", job: "内政官", recruitCost: 20, attackType: "magic", positionType: "後衛", range: 2, level: 1, hp: 27, maxHp: 27, mp: 4, maxMp: 4, atk: 6, pDef: 2, mDef: 5, agi: 6, policy: 25, growth: { hp: [2, 4], mp: 0, atk: 3, pDef: 1, mDef: 2, agi: 1 }, exp: 0, weaponBase: "杖", armorBase: "ローブ", weaponGrade: 0, armorGrade: 0, weapon: "革の杖", armor: "革のローブ", weaponAtk: 0, armorDef: 0, guildLevel: 2 },
  { name: "トーマ", job: "内政官", recruitCost: 24, attackType: "magic", positionType: "後衛", range: 2, level: 1, hp: 29, maxHp: 29, mp: 4, maxMp: 4, atk: 7, pDef: 2, mDef: 6, agi: 6, policy: 32, growth: { hp: [2, 4], mp: 0, atk: 3, pDef: 1, mDef: 2, agi: 1 }, exp: 0, weaponBase: "杖", armorBase: "ローブ", weaponGrade: 0, armorGrade: 0, weapon: "革の杖", armor: "革のローブ", weaponAtk: 0, armorDef: 0, guildLevel: 3 },
  { name: "リリア", job: "商人", recruitCost: 28, attackType: "physical", positionType: "前衛", range: 2, level: 1, hp: 31, maxHp: 31, mp: 7, maxMp: 7, atk: 7, pDef: 4, mDef: 4, agi: 8, policy: 8, growth: { hp: [22, 24], mp: 0, atk: 2, pDef: 1, mDef: 1, agi: 0 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 4 },
  { name: "セド", job: "内政官", recruitCost: 34, attackType: "magic", positionType: "後衛", range: 2, level: 1, hp: 31, maxHp: 31, mp: 5, maxMp: 5, atk: 8, pDef: 3, mDef: 7, agi: 7, policy: 40, growth: { hp: [4, 6], mp: 0, atk: 4, pDef: 1, mDef: 2, agi: 1 }, exp: 0, weaponBase: "杖", armorBase: "ローブ", weaponGrade: 0, armorGrade: 0, weapon: "革の杖", armor: "革のローブ", weaponAtk: 0, armorDef: 0, guildLevel: 6 },
  { name: "グレン", job: "商人", recruitCost: 40, attackType: "physical", positionType: "両方", range: 2, level: 1, hp: 34, maxHp: 34, mp: 8, maxMp: 8, atk: 8, pDef: 4, mDef: 5, agi: 9, policy: 17, growth: { hp: [25, 37], mp: 0, atk: 2, pDef: 1, mDef: 1, agi: 0 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 7 },
  { name: "ノア", job: "内政官", recruitCost: 46, attackType: "magic", positionType: "後衛", range: 2, level: 1, hp: 33, maxHp: 33, mp: 5, maxMp: 5, atk: 9, pDef: 3, mDef: 8, agi: 8, policy: 50, growth: { hp: [4, 6], mp: 0, atk: 4, pDef: 1, mDef: 3, agi: 1 }, exp: 0, weaponBase: "杖", armorBase: "ローブ", weaponGrade: 0, armorGrade: 0, weapon: "革の杖", armor: "革のローブ", weaponAtk: 0, armorDef: 0, guildLevel: 8 },
  { name: "ヴィオラ", job: "商人", recruitCost: 54, attackType: "physical", positionType: "両方", range: 3, level: 1, hp: 36, maxHp: 36, mp: 9, maxMp: 9, atk: 9, pDef: 5, mDef: 5, agi: 10, policy: 18, growth: { hp: [35, 37], mp: 0, atk: 4, pDef: 2, mDef: 2, agi: 2 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, guildLevel: 10 }
];

const monsters = [
  { name: "スライム", attackType: "physical", range: 1, hp: 10, mp: 3, atk: 6, pDef: 1, mDef: 1, agi: 5, exp: 4, gold: 3 },
  { name: "こうもり", attackType: "physical", range: 2, hp: 12, mp: 4, atk: 11, pDef: 2, mDef: 1, agi: 11, exp: 10, gold: 6 },
  { name: "ゴブリン", attackType: "physical", range: 1, hp: 18, mp: 4, atk: 10, pDef: 4, mDef: 2, agi: 6, exp: 9, gold: 8 },
  { name: "まどうし", attackType: "magic", range: 3, hp: 12, mp: 7, atk: 15, pDef: 1, mDef: 12, agi: 10, exp: 14, gold: 13 },
  { name: "塔の番人", attackType: "physical", range: 1, hp: 26, mp: 6, atk: 30, pDef: 6, mDef: 3, agi: 4, exp: 32, gold: 24 },
  { name: "影狼", attackType: "physical", range: 1, hp: 38, mp: 7, atk: 30, pDef: 3, mDef: 7, agi: 14, exp: 62, gold: 58 },
  { name: "黒騎士", attackType: "physical", range: 1, hp: 55, mp: 8, atk: 32, pDef: 14, mDef: 2, agi: 6, exp: 78, gold: 82 },
  { name: "闇司祭", attackType: "magic", range: 3, hp: 36, mp: 10, atk: 40, pDef: 1, mDef: 25, agi: 9, exp: 86, gold: 110 },
  { name: "骸骨剣士", attackType: "physical", range: 1, hp: 44, mp: 8, atk: 42, pDef: 10, mDef: 5, agi: 8, exp: 96, gold: 124 },
  { name: "火霊", attackType: "magic", range: 3, hp: 18, mp: 12, atk: 55, pDef: 3, mDef: 60, agi: 55, exp: 108, gold: 142 },
  { name: "鉄巨人", attackType: "physical", range: 1, hp: 102, mp: 8, atk: 88, pDef: 38, mDef: 1, agi: 1, exp: 270, gold: 380 },
  { name: "オーク", attackType: "physical", range: 1, hp: 204, mp: 10, atk: 66, pDef: 2, mDef: 1, agi: 1, exp: 410, gold: 460 },
  { name: "忍者", attackType: "physical", range: 2, hp: 25, mp: 14, atk: 88, pDef: 25, mDef: 14, agi: 38, exp: 450, gold: 580 },
  { name: "ダークピッグ", attackType: "both", range: 2, hp: 155, mp: 16, atk: 95, pDef: 32, mDef: 30, agi: 20, exp: 780, gold: 720 }
];

const equipmentGrades = [
  { name: "革", price: 0, atk: 0, def: 0 },
  { name: "銅", price: 30, atk: 4, def: 4 },
  { name: "鉄", price: 200, atk: 14, def: 14 },
  { name: "鋼", price: 1000, atk: 32, def: 32 },
  { name: "銀", price: 3260, atk: 55, def: 55 },
  { name: "金", price: 9420, atk: 75, def: 74 },
  { name: "クロ", price: 19650, atk: 100, def: 99 },
  { name: "ミス", price: 39950, atk: 126, def: 125 },
  { name: "ダ", price: 70350, atk: 153, def: 152 },
  { name: "オリ", price: 100850, atk: 181, def: 180 },
  { name: "ヒヒ", price: 210500, atk: 230, def: 229 }
];

const spritePalettes = {
  hero: { k: "#171410", s: "#f0bf82", t: "#d99264", e: "#ffe0b4", h: "#6f462a", d: "#3f2416", b: "#477bd3", y: "#f3d47c", w: "#f4f0e8", r: "#b9473f", g: "#5ac184", p: "#8f6bd8", v: "#5b438f", m: "#7e7465", c: "#64a8e8", n: "#2f5f8f", o: "#d98445", l: "#efe0b4" },
  monster: { k: "#171410", a: "#5ac184", b: "#3e8f68", c: "#f4f0e8", d: "#b9473f", e: "#64a8e8", f: "#8f6bd8", y: "#f3d47c", m: "#7e7465" }
};

const spritePatterns = {
  勇者: [
    "................",
    "......yyyy......",
    ".....yyyyyy.....",
    ".....hhhhhh.....",
    "....hssssssh....",
    "....swsswss....",
    "....ssrrss......",
    ".....srrrr......",
    "....bbbbbbbk....",
    "...bybbbbbk.....",
    "..bbybbbb.......",
    "....bbbb........",
    "....b..b........",
    "...kk..kk.......",
    "................",
    "................"
  ],
  戦士: [
    "................",
    ".....mmmmmm.....",
    "....mkkkkkkm....",
    "....mssssssm....",
    "....swswwss.....",
    "....ssssss......",
    "...rrrrrrrr.....",
    "..rmmmmmmrkk....",
    "..rmmmmmmrk.....",
    "...rrrrrr.......",
    "....bbbb........",
    "...bb..bb.......",
    "...kk..kk.......",
    "................",
    "................",
    "................"
  ],
  僧侶: [
    "................",
    "......wwww......",
    ".....wwyyww.....",
    ".....wssssw.....",
    ".....swswss.....",
    ".....ssssss.....",
    "....wwwpwww.....",
    "...wwwwpwww.....",
    "...wwwppwww.....",
    "....wwpww.......",
    "....bb.bb.......",
    "...kk..kk.......",
    "................",
    "................",
    "................",
    "................"
  ],
  魔法使い: [
    "................",
    ".......p........",
    "......ppp.......",
    ".....ppppp......",
    "....ppppppp.....",
    "......hhhh......",
    ".....swswss.....",
    ".....ssssss.....",
    "....ppppppp.....",
    "...ppppppppp....",
    "....pppppp......",
    "....bb..bb......",
    "...kk....kk.....",
    "................",
    "................",
    "................"
  ],
  盗賊: [
    "................",
    ".....kkkkkk.....",
    "....kggggggk....",
    "....gssssssg....",
    "....swswss......",
    "....ssssss......",
    "...gggggggg.....",
    "..ggrgggggkk....",
    "...gggggg.......",
    "....gggg........",
    "...bb..bb.......",
    "..kk....kk......",
    "................",
    "................",
    "................",
    "................"
  ],
  騎士: [
    "................",
    ".....wwwwww.....",
    "....wmmmmmmw....",
    "....mssssssm....",
    "....swswwss.....",
    "....ssssss......",
    "...wwwwwwww.....",
    "..wwwwwwwwkk....",
    "...wwwwww.......",
    "....wwww........",
    "...bb..bb.......",
    "..kk....kk......",
    "................",
    "................",
    "................",
    "................"
  ],
  スライム: [
    "................",
    "................",
    ".......a........",
    "......aaa.......",
    ".....aaaaa......",
    "....aaaaaaa.....",
    "...aaaaaaaaa....",
    "..aaacaaacaa....",
    "..aaaaaaaaaa....",
    "..aaaaaddaaa....",
    "...aaaaaaaa.....",
    "....bbbbbb......",
    "................",
    "................",
    "................",
    "................"
  ],
  こうもり: [
    "................",
    "................",
    "...m......m.....",
    "..mmm....mmm....",
    ".mmmmm..mmmmm...",
    "mmmmmmmmmmmmmm..",
    "...mmffffmm.....",
    "....fcffc.......",
    "....fffff.......",
    ".....ddf........",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................"
  ],
  ゴブリン: [
    "................",
    ".....a....a.....",
    "....aaaaaaaa....",
    "....acaaaca.....",
    "....aaaaaaa.....",
    ".....addda......",
    "...mmmmmmmm.....",
    "..mmymmmmmmk....",
    "....mmmmmm......",
    ".....m..m.......",
    "....kk..kk......",
    "................",
    "................",
    "................",
    "................",
    "................"
  ],
  まどうし: [
    "................",
    ".......f........",
    "......fff.......",
    ".....fffff......",
    "....fffffff.....",
    "......mmmm......",
    ".....mcfcmm.....",
    ".....mmmmm......",
    "....ffffffff....",
    "...ffffyffff....",
    "....fffff.......",
    "....m..m........",
    "...kk..kk.......",
    "................",
    "................",
    "................"
  ],
  塔の番人: [
    "................",
    "....m....m......",
    "...mmmmmmmm.....",
    "..mmmyyyymm.....",
    "..mycmmycym.....",
    "..myyyyyyym.....",
    "...mddddm.......",
    "..mmmmmmmm......",
    ".mmmmmmmmmm.....",
    "...mmmmmm.......",
    "..mm....mm......",
    ".kk......kk.....",
    "................",
    "................",
    "................",
    "................"
  ],
  天塔竜: [
    ".......d........",
    "......ddd.......",
    ".....ddddd......",
    "...dddyyddd.....",
    "..ddycyycdd.....",
    "..ddyyyyddd.....",
    "...ddddd........",
    "..mmmmmmmm......",
    ".mmmmmmmmmm.....",
    "mmmmmmmmmmmm....",
    "...mm..mm.......",
    "..kk....kk......",
    "................",
    "................",
    "................",
    "................"
  ]
};

Object.assign(spritePatterns, {
  影狼: [
    "................",
    "..m......m......",
    ".mmm....mmm.....",
    ".mmmmmmmmmm.....",
    "mmmfmmmfmmm.....",
    "mmmmmmmmmmm.....",
    "..mmmdddmm......",
    "...mmmmmm.......",
    "..mmmmmmmm......",
    ".mmm.mmmm.m.....",
    "mm...mm...mm....",
    "k....kk....k....",
    "................",
    "................",
    "................",
    "................"
  ],
  黒騎士: [
    "................",
    ".....mmmmmm.....",
    "....mkkkkkkm....",
    "...mmmyyyymmm...",
    "...mkmccmckm....",
    "...mmyyyyymm....",
    "....mddddm......",
    "...mmmmmmmmk....",
    "..mmmmmmmmmk....",
    ".kmmmmmmmmk.....",
    "...mmmmmm.......",
    "...mm..mm.......",
    "..kk....kk......",
    "................",
    "................",
    "................"
  ],
  闇司祭: [
    "................",
    ".......f........",
    "......fff.......",
    ".....fffff......",
    "....ffmmmff.....",
    "....fmcccmf.....",
    "....fmmmmm......",
    "...ffffffff.....",
    "..ffffyffffk....",
    "...fffffffk.....",
    "....fffff.......",
    "....m..m........",
    "...kk..kk.......",
    "................",
    "................",
    "................"
  ],
  骸骨剣士: [
    "................",
    ".....cccccc.....",
    "....cckyykcc....",
    "....ckcccckc....",
    ".....cddddc.....",
    "...mmmmmmmmk....",
    "..mmcyyyycmm....",
    "...mmmmmmmm.....",
    "....m..m........",
    "...mm..mm.......",
    "..kk....kk......",
    "................",
    "................",
    "................",
    "................",
    "................"
  ],
  火霊: [
    ".......d........",
    "......ddd.......",
    ".....ddydd......",
    "....ddyyddd.....",
    "...ddyyyyddd....",
    "...ddycydydd....",
    "..ddyyyyyyddd...",
    "..dddydddyd.....",
    "...ddyyyydd.....",
    "....dddddd......",
    ".....dddd.......",
    "................",
    "................",
    "................",
    "................",
    "................"
  ],
  鉄巨人: [
    "................",
    "....mmmmmmmm....",
    "...mmkkkkkkmm...",
    "..mmmyyyymmmm...",
    "..mkmccmckmmm...",
    "..mmyyyyymmm....",
    "...mddddmmm.....",
    "..mmmmmmmmmm....",
    ".mmmmmmmmmmmm...",
    ".mmmmmmmmmmmm...",
    "...mmmmmmmm.....",
    "..mmm....mmm....",
    ".kkk......kkk...",
    "................",
    "................",
    "................"
  ]
});

Object.assign(spritePatterns, {
  勇者: [
    "........................",
    "..........yyyy..........",
    ".........yyyyyy.........",
    "........yyywwyyy........",
    ".......yyhhhhhhyy.......",
    ".......yhhhhhhhhy.......",
    "......hhsssssshh........",
    "......hsswsswssh........",
    "......hssssssssh........",
    ".......ssrrrrss.........",
    "........srrrrs..........",
    "......bbbbbbbbbb........",
    ".....bbybbbbbybb........",
    "....bbbybbbbbybbb.......",
    "....bbbyyyyyybbb........",
    ".....bbbbbbbbbb.........",
    "......bb....bb..........",
    "......bb....bb..........",
    ".....kkk....kkk.........",
    "....kkkk....kkkk........",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  戦士: [
    "........................",
    "........mmmmmmmm........",
    ".......mmkkkkkkmm.......",
    "......mmkkkkkkkkmm......",
    "......mmssssssssmm......",
    "......msswsswwssm.......",
    "......msssssssssm.......",
    ".......sssrrrrss........",
    "......rrrrrrrrrrrr......",
    ".....rrmmmmmmmmrrk......",
    "....rrmmmmmmmmmmrk......",
    "...kkkmmmmmmmmmmrk......",
    ".....rrmmmmmmmmrr.......",
    "......rrrrrrrrrr........",
    ".......bbbbbbbb.........",
    "......bbb....bbb........",
    "......bb......bb........",
    ".....kkk......kkk.......",
    "....kkkk......kkkk......",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  僧侶: [
    "........................",
    ".........wwwwww.........",
    "........wwyyyyww........",
    ".......wwwyyyywww.......",
    ".......wwssssssww.......",
    ".......wsswsswssw.......",
    ".......wssssssssw.......",
    "........sssllss.........",
    ".......wwwwpwwww........",
    "......wwwwwpwwwww.......",
    ".....wwwwpppwwwww.......",
    ".....wwwppwppwwww.......",
    "......wwwpppwwww........",
    ".......wwwpwwww.........",
    "........wwwwww..........",
    "........bb..bb..........",
    ".......bbb..bbb.........",
    "......kkk....kkk........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  魔法使い: [
    "........................",
    "...........p............",
    "..........ppp...........",
    ".........ppppp..........",
    "........ppppppp.........",
    ".......ppppppppp........",
    "......pppccccppp........",
    "........hhhhhh..........",
    ".......hssssssh.........",
    ".......sswsswss.........",
    ".......ssssssss.........",
    "......pppppppppp........",
    ".....pppppppppppp.......",
    "....ppppppyypppp........",
    "....pppppppppppp........",
    "......pppppppp..........",
    ".......bb....bb.........",
    "......kkk....kkk........",
    ".....kkkk....kkkk.......",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  盗賊: [
    "........................",
    "........kkkkkkkk........",
    ".......kkggggggkk.......",
    "......kkggggggggkk......",
    "......kgssssssssgk......",
    "......gsswsswssg........",
    "......gsssssssg.........",
    ".......sssrrss..........",
    "......gggggggggg........",
    ".....ggggngggggkk.......",
    "....ggggnnggggkk........",
    "...kkgggnggggg..........",
    ".....gggggggg...........",
    "......gggggg............",
    ".......bb..bb...........",
    "......bbb..bbb..........",
    ".....kkk....kkk.........",
    "....kkkk....kkkk........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  騎士: [
    "........................",
    ".........wwwwww.........",
    "........wwmmmmww........",
    ".......wwmmmmmmww.......",
    ".......wmssssssmw.......",
    ".......msswsswwsm.......",
    ".......msssssssm........",
    "........sssrrss.........",
    "......wwwwwwwwww........",
    ".....wwwwwwwwwwwwk......",
    "....wwwwwwwwwwwwwk......",
    "...kkwwwwwwwwwwwwk......",
    ".....wwwwwwwwwwww.......",
    "......wwwwwwwwww........",
    ".......bb....bb.........",
    "......bbb....bbb........",
    ".....kkk......kkk.......",
    "....kkkk......kkkk......",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ]
});

const heroPortrait32Patterns = {
  アルス: [
    "................................",
    "................................",
    ".............kkkkkk.............",
    "..........kkkddddddkkk..........",
    ".........kddhhhhhhhddk..........",
    "........kdhhhhhhhhhhhdk.........",
    ".......kdhhhhhhhhhhhhdk.........",
    "......kdhhhyyyyyyhhhhdk.........",
    "......kdhhyyyyyyyyhhhdk.........",
    ".....kdhhyyyyyyyyyyhhdk.........",
    ".....kdhhheeessseeehhdk.........",
    ".....kdheesssssssssedk..........",
    ".....kdhessksssskssehk..........",
    ".....kdhesskcssckssedk..........",
    ".....kdhessssssssssedk..........",
    ".....kdhesssttttsssedk..........",
    "......kdhessrrrrssedk...........",
    "......kdhessssssssedk...........",
    ".......kdheesssssedk............",
    "........kddheeeehddk............",
    ".........kkddddddkk.............",
    "..........kbbbbbbk..............",
    ".........kbbbyybbbk.............",
    "........kbbbbbbbbbbk............",
    ".......kbbbbbbbbbbbbk...........",
    ".......kkbbbbbbbbbbkk...........",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................"
  ],
  ガロン: [
    "................................",
    "................................",
    "........k................k......",
    ".......kmmk............kmmk.....",
    "......kmmmmkkkkkkkkkkkmmmmk.....",
    ".....kmmmmmmmmmmmmmmmmmmmmk.....",
    "....kmmmmddddddddddddmmmmmk.....",
    "...kmmmddhhhhhhhhhhddmmmmmk.....",
    "...kmmddhhhhhhhhhhhhddmmmmk.....",
    "..kmmddhheessssssseehddmmmk.....",
    "..kmmddheesssssssssehddmmmk.....",
    "..kmmddhessksssskssehddmmmk.....",
    "..kmmddhesskcssckssedddmmmk.....",
    "..kmmddhessssssssssedddmmmk.....",
    "..kmmddhesssttttsssedddmmmk.....",
    "...kmmddhessrrrrssedddmmmk......",
    "...kmmdddheesssseddddmmmk.......",
    "....kmmddddhhhhddddmmmk.........",
    ".....kmmmmddddddmmmmmk..........",
    "......kmmmmmmmmmmmmmk...........",
    ".......kkmmmmmmmmmmkk...........",
    ".........kkkmmmmkkk.............",
    "..........krrrrrrk..............",
    ".........krrrrrrrrk.............",
    "........krrrrrrrrrrk............",
    ".......kkrrrrrrrrrrkk...........",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................"
  ],
  ミリア: [
    "................................",
    "................................",
    "............kkkkkkkk............",
    "..........kkwwwwwwwwkk..........",
    ".........kwwwwyyyywwwwk.........",
    "........kwwyyyyyyyywwwwk........",
    ".......kwwyyyyyyyyyywwwk........",
    "......kwwyyyyeeeeyyyywwk........",
    "......kwwyyyeeeeeeyyywwk........",
    ".....kwwyyyeesssseeyyywwk.......",
    ".....kwwyyeesssssseeyywwk.......",
    ".....kwwyesskssssksseywwk.......",
    ".....kwwyesskcssckssywwk........",
    ".....kwwyessssssssssywwk........",
    ".....kwwyesssttttsssywwk........",
    "......kwwyessrrrrssywwk.........",
    "......kwwyeessssssywwk..........",
    ".......kwwyyeessyywwk...........",
    "........kwwwyyyywwwk............",
    ".........kkwwwwwwkk.............",
    "..........kwwppwwk..............",
    ".........kwwppppwwk.............",
    "........kwwwppppwwwk............",
    ".......kwwwwppppwwwwk...........",
    "......kkwwwwppppwwwwkk..........",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................"
  ],
  セネカ: [
    "................................",
    "...............kk...............",
    "..............kppk..............",
    ".............kppppk.............",
    "............kppppppk............",
    "...........kppppppppk...........",
    "..........kppppppppppk..........",
    ".........kppppppppppppk.........",
    "........kppppccccccppppk........",
    ".......kppppkkkkkkkkppppk.......",
    "...........kddddddddk...........",
    "..........kddhhhhhhddk..........",
    ".........kdhheeeeeehhdk.........",
    ".........kdheessssssehk.........",
    ".........kdhesskssskedk.........",
    ".........kdhesskccskedk.........",
    ".........kdhessssssssedk........",
    ".........kdhessstttsedk.........",
    "..........kdheerrssedk..........",
    "..........kddheeeehddk..........",
    "...........kkddddddkk...........",
    ".........kpppvvvvvvpppk.........",
    "........kppppvvvvvvppppk........",
    ".......kppppppvvvvppppppk.......",
    "......kkppppppppppppppppkk......",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................"
  ],
  イモス: [
    "................................",
    "................................",
    "............kkkkkkkk............",
    "..........kkggggggggkk..........",
    ".........kggggnnnnngggk.........",
    "........kgggnnnnnnnngggk........",
    ".......kggnnnnnnnnnnnggk........",
    "......kggnnnnkkkkknnnngk........",
    "......kggnnnkeeeeknnnngk........",
    ".....kggnnkeesssseeknnngk.......",
    ".....kggnkeesssssseeknngk.......",
    ".....kggnkesskssssksengk........",
    ".....kggnkesskcsscksengk........",
    ".....kggnkesssssssssenk.........",
    ".....kggnkesssttttssenk.........",
    "......kggnkessrrrrsenk..........",
    "......kggnkeesssssengk..........",
    ".......kggnnkeeeeknngk..........",
    "........kggnnkkkkknngk..........",
    ".........kkggnnnnnggkk..........",
    "...........kkggggkk.............",
    "............kggggk..............",
    "...........kggggggk.............",
    "..........kgggkkgggk............",
    ".........kkggk..kggkk...........",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................"
  ],
  ノルン: [
    "................................",
    "................................",
    "............kkkkkkkk............",
    "..........kkmmmmmmmmkk..........",
    ".........kmmmmwwmmmmmmk.........",
    "........kmmmmwwwwmmmmmmk........",
    ".......kmmmwwwwwwwwmmmmk........",
    "......kmmmwwkkkkkkwwmmmk........",
    "......kmmwwkddddddkwwmmk........",
    ".....kmmwwkdheeeehdkwwmmk.......",
    ".....kmmwwkheesssehkwwmmk.......",
    ".....kmmwwkhessssshkwwmmk.......",
    ".....kmmwwkhkcssckhkwwmmk.......",
    ".....kmmwwkhsssssshkwwmmk.......",
    ".....kmmwwkhsttttshkwwmmk.......",
    "......kmmwwkhsrrrshkwwmk........",
    "......kmmwwkheessehkwwmk........",
    ".......kmmwwkheehkwwmmk.........",
    "........kmmmwwkkwwmmmk..........",
    ".........kkmmmmmmmmkk...........",
    "...........kkkkkkkk.............",
    "..........kmmmmmmmmk............",
    ".........kmmmmmmmmmmk...........",
    "........kmmmmmmmmmmmmk..........",
    ".......kkmmmmmmmmmmmmkk.........",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................",
    "................................"
  ]
};

const heroSprite16x24Patterns = {
  アルス: [
    "................",
    ".....kkkkk......",
    "....khyyyyk.....",
    "...khyyyyyyk....",
    "...kyhssssyk....",
    "...khsswssyk....",
    "..rkhsssssykr...",
    ".rrkhssrrsykrr..",
    "rrrbbbbbbbbkww..",
    "rrbbbbbyybbkww..",
    "rbbbbbyyyybbkw..",
    ".bbbbbbbbbbbk...",
    "..bbbbbbbbbbk...",
    "...bbbbbbbb.....",
    "...bb...bbb.....",
    "..bbb...bbbb....",
    ".bbbb....bbb....",
    ".kkk.....kkk....",
    "kkk......kkkk...",
    "...........kw...",
    "..........kkw...",
    ".........kk.....",
    "........kk......",
    "................"
  ],
  ガロン: [
    "................",
    "k.....k....k....",
    "kk...kmk..kmk...",
    ".kk.kmmkkkkmmk..",
    "..kkmmmmmmmmmk..",
    "...kmmmmmmmmmk..",
    "..kmmkhhhhkhmmk.",
    "..kmmhssssshmmk.",
    "..kmmhswsswhmmk.",
    "..kmmhssrrshmmk.",
    ".rrkmmhrrrrhmmk.",
    "rrrmmmmmmmmmmrk.",
    "rrmmmmmmmmmmmrrk",
    ".rrmmmmmmmmmmrr.",
    "..rrrmmmmmmrrr..",
    "...rrrmmmmrr....",
    "....rrbbbbrr....",
    ".....bbbbbb.....",
    "....bbb..bbb....",
    "...bbbb..bbbb...",
    "..kkkk....kkkk..",
    "...........kkkk.",
    "............kk..",
    "................"
  ],
  ミリア: [
    "................",
    ".....kkkkkk.....",
    "....kwwwwwwk....",
    "...kwwyyyywwk...",
    "..kwwyyyyyywwk..",
    "..kwwyssssywwk..",
    ".kwwysswwssywwk.",
    ".kwwyssssssywwk.",
    ".kwwyssllssywwk.",
    "..kwwppppppwwk..",
    ".kwwwppppppwwwk.",
    "kwwwwppwwppwwwwk",
    "kwwwwppwwppwwwwk",
    ".kwwwppppppwwwk.",
    "..kwwppppppwwk..",
    "...kwwwwwwwwk...",
    "....kbbbbbbk....",
    ".....bb..bb.....",
    "....bbb..bbb....",
    "...kkkk..kkkk...",
    "......y.........",
    ".....yyy........",
    "......y.........",
    "................"
  ]
};

Object.assign(spritePatterns, {
  アルス: [
    "........................",
    ".........kkkkkk.........",
    ".......kkyyyyyykk.......",
    "......kyyyyyyyyyyk......",
    ".....kyyyyyyyyyyyyk.....",
    "....kyyyhbbbbhhyyyk.....",
    "....kyyhsssssshhyyk.....",
    "...kyyhsssssssshhyyk....",
    "...kyhsskwsswksshhyk....",
    "...kyhsssssssssshhyk....",
    "...kyhsssrrrrssshhyk....",
    "...kyyhsssssssshhyyk....",
    "....kyyhsssssshhyyk.....",
    ".....kyyhhhhhhyyyk......",
    "......kyyyyyyyyyk.......",
    ".......kkyyyyyykk.......",
    ".........kkkkkk.........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  ガロン: [
    "........................",
    "......kk........kk......",
    ".....kmmk......kmmk.....",
    "....kmmmmkkkkkkmmmmk....",
    "...kmmmmmmmmmmmmmmmmk...",
    "...kmmmkkkkkkkkkkmmmk...",
    "..kmmmksssssssskkmmmk...",
    "..kmmksskwsswksskkmmk...",
    "..kmmksssssssssskkmmk...",
    "..kmmkssshhhhssskkmmk...",
    "..kmmksshhhhhhsskkmmk...",
    "...kmmkshddddhskkmmk....",
    "...kmmkshddddhskmmmk....",
    "....kmmkshhhhskmmmk.....",
    ".....kmmkkkkkkmmmk......",
    "......kmmmmmmmmk........",
    ".......kkmmmmkk.........",
    ".........kkkk...........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  ミリア: [
    "........................",
    ".........kkkkkk.........",
    ".......kkwwwwwwkk.......",
    "......kwwyyyyyywwk......",
    ".....kwwwyyyyyywwwk.....",
    "....kwwwsssssssswwwk....",
    "....kwwsssssssssswwk....",
    "...kwwsskwsswksswwk.....",
    "...kwwsssssssssswwk.....",
    "...kwwsssllllssswwk.....",
    "...kwwwsssssssswwwk.....",
    "....kwwwsssssswwwk......",
    ".....kwwwppppwwwk.......",
    "......kwwppppwwk........",
    ".......kwwwwwwk.........",
    "........kkwwkk..........",
    "..........kk............",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  セネカ: [
    "........................",
    "...........kk...........",
    "..........kppk..........",
    ".........kppppk.........",
    "........kppppppk........",
    ".......kppppppppk.......",
    "......kppppppppppk......",
    ".....kpppccccccpppk.....",
    "....kppkkkkkkkkppppk....",
    ".......khhhhhhhk........",
    "......khssssssshk.......",
    "......ksskwsswkssk......",
    "......kssssssssssk......",
    "......ksssddddsssk......",
    ".......khhddddhhk.......",
    "........kppppppk........",
    ".......kppppppppk.......",
    "......kppppppppppk......",
    ".......kkkkkkkkkk.......",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  イモス: [
    "........................",
    ".........kkkkkk.........",
    ".......kkggggggkk.......",
    "......kggggggggggk......",
    ".....kgggkkkkkkgggk.....",
    "....kggksssssssskgk.....",
    "....kgksssssssssskk.....",
    "...kgksskwsswksssk......",
    "...kgksssssssssssk......",
    "...kgksssrrrrssskk......",
    "...kggksssssssskgk......",
    "....kggksssssskgk.......",
    ".....kggkkkkkkggk.......",
    "......kggggggggk........",
    ".......kkggggkk.........",
    ".........kkkk...........",
    "...........kkk..........",
    "..........kkkkk.........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  ノルン: [
    "........................",
    ".........kkkkkk.........",
    ".......kkmmmmmmkk.......",
    "......kmmmmmmmmmmk......",
    ".....kmmmwwwwwwmmmk.....",
    "....kmmmwsssssswmmmk....",
    "....kmmwsssssssswmmk....",
    "...kmmwsskwsswksswmmk...",
    "...kmmwsssssssssswmmk...",
    "...kmmwsssrrrrssswmmk...",
    "...kmmwsssssssssswmmk...",
    "....kmmwsssssssswmmk....",
    ".....kmmmwsssswmmmk.....",
    "......kmmmmmmmmmmk......",
    ".......kkmmmmmmkk.......",
    ".........kkkkkk.........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  エルマ: [
    "........................",
    ".........kkkkkk.........",
    ".......kkwwwwwwkk.......",
    "......kwwllllllwwk......",
    ".....kwwllllllllwwk.....",
    "....kwwllssssssllwwk....",
    "....kwllssssssssllwk....",
    "...kwllsskwsswkssllwk...",
    "...kwllssssssssssllwk...",
    "...kwllsssrrrrsssllwk...",
    "...kwwllssssssssllwwk...",
    "....kwwllssssssllwwk....",
    ".....kwwwllllllwwwk.....",
    "......kwwwwwwwwwwk......",
    ".......kkwwwwwwkk.......",
    ".........kkkkkk.........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  ダブチ: [
    "........................",
    ".........kkkkkk.........",
    "......kkooooooookk......",
    "......koooooooooook.....",
    ".....koookkkkkoooook....",
    "....koooksssskoooook....",
    "....kooksssssskoook.....",
    "...kooksskwsswksskoook..",
    "...kooksssssssskoook....",
    "...kooksssrrrrsskoook...",
    "...kookssshhhhsskoook...",
    "....kookshddddhkoook....",
    ".....koookddddkoook.....",
    "......koookkkkoook......",
    ".......kkoooooook.......",
    ".........kkkkkk.........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  サイラス: [
    "........................",
    "..........kkkk..........",
    "........kkppppkk........",
    ".......kppppppppk.......",
    "......kppppppppppk......",
    ".....kpppkkkkkkpppk.....",
    "....kpppkwwwwwwkpppk....",
    "....kppkwsssssswkppk....",
    "...kppkwsskwsswksskpk...",
    "...kppkwsssssssssskpk...",
    "...kppkwsssddddssskpk...",
    "...kpppkwddddddwkppk....",
    "....kpppkwddddwkppk.....",
    ".....kpppkkkkkkppk......",
    "......kpppppppppk.......",
    ".......kkppppppkk.......",
    ".........kkkkkk.........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  フィオナ: [
    "........................",
    ".........kkkkkk.........",
    ".......kkrrrrrrkk.......",
    "......krrrrrrrrrrk......",
    ".....krrroooooorrrk.....",
    "....krroossssssoorrk....",
    "....kroossssssssoork....",
    "...kroosskwsswkssoork...",
    "...kroossssssssssoork...",
    "...kroosssrrrrsssoork...",
    "...krroossssssssoorrk...",
    "....krroossssssoorrk....",
    ".....krrroooooorrrk.....",
    "......krrrrrrrrrrk......",
    ".......kkrrrrrrkk.......",
    ".........kkkkkk.........",
    "............kk..........",
    "...........kkkk.........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  ピッポ: [
    "........................",
    ".........kkkkkk.........",
    ".......kkmmmmmmkk.......",
    "......kmmmmmmmmmmk......",
    ".....kmmwwwwwwwwmmk.....",
    "....kmmwwkkkkkkwwmmk....",
    "....kmmwksssssskwmmk....",
    "...kmmwksskwsswksskwmk..",
    "...kmmwksssssssssskwmk..",
    "...kmmwksssrrrrssskwmk..",
    "...kmmwksssssssssskwmk..",
    "....kmmwksssssskwmmk....",
    ".....kmmwwkkkkwwmmk.....",
    "......kmmmmmmmmmmk......",
    ".......kkmmmmmmkk.......",
    ".........kkkkkk.........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  カリン: [
    "........................",
    ".........kkkkkk.........",
    ".......kkyyyyyykk.......",
    "......kyyyyyyyyyyk......",
    ".....kyyyrrrrrryyyk.....",
    "....kyyyssssssssyyyk....",
    "....kyyssssssssssyyk....",
    "...kyysskwsswksssyyk....",
    "...kyysssssssssssyyk....",
    "...kyysssrrrrsssyyyk....",
    "...kyyyssssssssyyyk.....",
    "....kyyyssssssyyyk......",
    ".....kyyyyyyyyyyk.......",
    "......kyyyyyyyyk........",
    ".......kkyyyykk.........",
    ".........kkkk...........",
    "...........kyy..........",
    "..........kyyyy.........",
    ".........kyyyyyy........",
    "..........kkkk..........",
    "........................",
    "........................",
    "........................",
    "........................"
  ]
});

Object.assign(spritePatterns, {
  勇者: [
    "........................",
    ".........yyyyyy.........",
    "........yyywwyyy........",
    ".......yyyhhhhyyy.......",
    ".......yyhhhhhhyy.......",
    "......yyhsssssshyy......",
    "......yhsswsswsshy......",
    "......yhsssssssshy......",
    ".......hssrrrrssh.......",
    ".....rrrssrrrrssrr......",
    "....rrrrbbbbbbbbrr......",
    "...rrrrbbbyyybbbrrk.....",
    "...rrrbbbyyyyybbbkk.....",
    "..rrrbbbbbbbbbbbkk......",
    "...rrrbbbbbbbbbbk.......",
    "....rrrbbbbbbbb.........",
    ".....rrbb....bb.........",
    "......bbb....bbb........",
    ".....bbbb....bbbb.......",
    "....kkkk......kkkk......",
    ".................k......",
    "................kk......",
    "...............kk.......",
    "........................"
  ],
  戦士: [
    "........................",
    "........m....m..........",
    ".......mmm..mmm.........",
    "......mmmmmmmmmm........",
    ".....mmmkkkkkkmmm.......",
    ".....mmksssssskm........",
    ".....mksswsswsskm.......",
    ".....mksssssssskm.......",
    "......mssrrrrssm........",
    "....rrrrmmmmmmrrrr......",
    "...rrrmmmmmmmmmmrrrk....",
    "..rrmmmmmmmmmmmmrrkk....",
    ".kkkmmmmmmmmmmmmrrkk....",
    "...rrmmmmmmmmmmrrr......",
    "....rrrrmmmmmmrrr.......",
    "......rrbbbbbbrr........",
    ".......bbbbbbbb.........",
    "......bbb....bbb........",
    ".....bbbb....bbbb.......",
    "....kkkk......kkkk......",
    "................kk......",
    "...............kkkk.....",
    "................kk......",
    "........................"
  ],
  僧侶: [
    "........................",
    "..........wwww..........",
    ".........wwyyww.........",
    "........wwwyywww........",
    ".......wwwsssswww.......",
    ".......wwsswssww........",
    ".......wwssssssww.......",
    "........wssllssw........",
    ".....y..wwwppwww........",
    ".....y.wwwwppwwww.......",
    "....yyywwwppppwww.......",
    ".....ywwwwpwwpwww.......",
    ".....ywwwwppppwww.......",
    ".....y.wwwwppwwww.......",
    ".....y..wwwppwww........",
    ".....y...wwwwww.........",
    ".....y....bb..bb........",
    "....yyy..bbb..bbb.......",
    "..........kk..kk........",
    ".........kkk..kkk.......",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  魔法使い: [
    "........................",
    "...........p............",
    "..........ppp...........",
    ".........ppppp..........",
    "........ppppppp.........",
    ".......ppppppppp........",
    "......ppppccccppp.......",
    ".....pppppppppppp.......",
    "........hhhhhh..........",
    ".......hssssssh.........",
    ".......sswsswss.........",
    "......hssssssss.........",
    ".....pppppppppppp.......",
    "....pppppppppppppp......",
    "...ppppppyyppppppp......",
    "...ppppppppppppppk......",
    "..kpppppppppppppkk......",
    ".kkk..pppppppp..........",
    "..k....bb....bb.........",
    "......bbb....bbb........",
    ".....kkkk....kkkk.......",
    "................yy......",
    "...............yyyy.....",
    "........................"
  ],
  盗賊: [
    "........................",
    ".........kkkkkk.........",
    "........kkggggkk........",
    ".......kkggggggkk.......",
    ".......kgssssssgk.......",
    "......kgsswsswssg.......",
    "......kgsssssssg........",
    ".......gssrrssg.........",
    ".....ggggggrgggg........",
    "....gggggggggggk........",
    "...kgggggnngggkk........",
    "..kkgggggnnggkk.........",
    ".kk..gggggggg...........",
    ".....gggggggg...........",
    "......gggggg............",
    "......bbb..bbb..........",
    ".....bbbb..bbbb.........",
    "....kkkk....kkkk........",
    "...kk............kk.....",
    "..kk..............kk....",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  騎士: [
    "..........w.............",
    ".........www............",
    "........wwmww...........",
    ".......wwmmmww..........",
    ".......wmssssmw.........",
    "......wmsswsswwm........",
    "......wmssssssmw........",
    ".......mssrrssm.........",
    ".....wwwwwwwwww.........",
    "....wwwwwwwwwwwwk.......",
    "...wwwwwwwwwwwwwkk......",
    "..kwwwwwwwwwwwwwkk......",
    ".kkwwwwwwwwwwwwwkk......",
    "..kwwwwwwwwwwwwwk.......",
    "...wwwwwwwwwwwww........",
    "....wwwwwwwwwww.........",
    "......bbb....bbb........",
    ".....bbbb....bbbb.......",
    "....kkkk......kkkk......",
    "..................k.....",
    ".................kk.....",
    "................kk......",
    "...............kk.......",
    "........................"
  ]
});

Object.assign(spritePatterns, heroPortrait32Patterns);
Object.assign(spritePatterns, heroSprite16x24Patterns);
