const DEFAULT_GROWTH = { hp: [5, 8], mp: 0, atk: 2, def: 1, agi: 1 };

const startingMembers = [
  { name: "アルス", job: "勇者", positionType: "両方", range: 1, level: 1, hp: 34, maxHp: 34, mp: 8, maxMp: 8, atk: 8, def: 4, agi: 8, policy: 3, growth: { hp: [5, 7], mp: 2, atk: 2, def: 1, agi: 1 }, exp: 0, weaponBase: "剣", armorBase: "鎧", weaponGrade: 0, armorGrade: 0, weapon: "革の剣", armor: "革の鎧", weaponAtk: 0, armorDef: 0 },
  { name: "ガロン", job: "戦士", positionType: "前衛", range: 1, level: 1, hp: 42, maxHp: 42, mp: 0, maxMp: 0, atk: 10, def: 6, agi: 5, policy: 1, growth: { hp: [7, 10], mp: 0, atk: 3, def: 2, agi: 0 }, exp: 0, weaponBase: "斧", armorBase: "鎧", weaponGrade: 0, armorGrade: 0, weapon: "革の斧", armor: "革の鎧", weaponAtk: 0, armorDef: 0 }
];

const recruitableMembers = [
  { name: "ミリア", job: "僧侶", positionType: "後衛", range: 2, level: 1, hp: 28, maxHp: 28, mp: 14, maxMp: 14, atk: 5, def: 3, agi: 6, policy: 4, growth: { hp: [4, 6], mp: 4, atk: 1, def: 1, agi: 1 }, exp: 0, weaponBase: "杖", armorBase: "ローブ", weaponGrade: 0, armorGrade: 0, weapon: "革の杖", armor: "革のローブ", weaponAtk: 0, armorDef: 0, joinFloor: 8 },
  { name: "セネカ", job: "魔法使い", positionType: "後衛", range: 3, level: 1, hp: 24, maxHp: 24, mp: 18, maxMp: 18, atk: 6, def: 2, agi: 7, policy: 5, growth: { hp: [3, 5], mp: 5, atk: 1, def: 0, agi: 1 }, exp: 0, weaponBase: "杖", armorBase: "ローブ", weaponGrade: 0, armorGrade: 0, weapon: "革の杖", armor: "革のローブ", weaponAtk: 0, armorDef: 0, joinFloor: 16 },
  { name: "リオ", job: "盗賊", positionType: "両方", range: 2, level: 1, hp: 30, maxHp: 30, mp: 4, maxMp: 4, atk: 7, def: 3, agi: 12, policy: 2, growth: { hp: [4, 6], mp: 1, atk: 2, def: 1, agi: 2 }, exp: 0, weaponBase: "短剣", armorBase: "服", weaponGrade: 0, armorGrade: 0, weapon: "革の短剣", armor: "革の服", weaponAtk: 0, armorDef: 0, joinFloor: 24 },
  { name: "ノルン", job: "騎士", positionType: "前衛", range: 2, level: 1, hp: 38, maxHp: 38, mp: 0, maxMp: 0, atk: 9, def: 7, agi: 4, policy: 2, growth: { hp: [6, 9], mp: 0, atk: 2, def: 3, agi: 0 }, exp: 0, weaponBase: "槍", armorBase: "鎧", weaponGrade: 0, armorGrade: 0, weapon: "革の槍", armor: "革の鎧", weaponAtk: 0, armorDef: 0, joinFloor: 32 }
];

const monsters = [
  { name: "スライム", range: 1, hp: 12, atk: 5, def: 1, agi: 5, exp: 4, gold: 3 },
  { name: "こうもり", range: 2, hp: 15, atk: 6, def: 2, agi: 11, exp: 9, gold: 6 },
  { name: "ゴブリン", range: 1, hp: 22, atk: 8, def: 3, agi: 6, exp: 9, gold: 8 },
  { name: "まどうし", range: 3, hp: 26, atk: 10, def: 2, agi: 7, exp: 14, gold: 13 },
  { name: "塔の番人", range: 1, hp: 42, atk: 14, def: 5, agi: 4, exp: 25, gold: 24 },
  { name: "影狼", range: 1, hp: 58, atk: 18, def: 6, agi: 14, exp: 62, gold: 58 },
  { name: "黒騎士", range: 1, hp: 76, atk: 22, def: 10, agi: 6, exp: 78, gold: 72 },
  { name: "闇司祭", range: 3, hp: 62, atk: 24, def: 7, agi: 9, exp: 86, gold: 90 }
];

const equipmentGrades = [
  { name: "革", price: 0, atk: 0, def: 0 },
  { name: "銅", price: 30, atk: 2, def: 2 },
  { name: "鉄", price: 70, atk: 4, def: 4 },
  { name: "鋼", price: 140, atk: 7, def: 7 },
  { name: "銀", price: 260, atk: 11, def: 10 },
  { name: "金", price: 420, atk: 15, def: 14 },
  { name: "クロ", price: 650, atk: 20, def: 19 },
  { name: "ミス", price: 950, atk: 26, def: 25 },
  { name: "ダ", price: 1350, atk: 33, def: 32 },
  { name: "オリ", price: 1850, atk: 41, def: 40 },
  { name: "ヒヒ", price: 2500, atk: 50, def: 49 }
];

const spritePalettes = {
  hero: { k: "#171410", s: "#f0bf82", h: "#6f462a", b: "#477bd3", y: "#f3d47c", w: "#f4f0e8", r: "#b9473f", g: "#5ac184", p: "#8f6bd8", m: "#7e7465", c: "#64a8e8", n: "#2f5f8f", o: "#d98445", l: "#efe0b4" },
  monster: { k: "#171410", a: "#5ac184", b: "#3e8f68", c: "#f4f0e8", d: "#b9473f", e: "#64a8e8", f: "#8f6bd8", y: "#f3d47c", m: "#7e7465" }
};

const spritePatterns = {
  勇者: [
    "................",
    "......yyyy......",
    ".....yyyyyy.....",
    ".....hhhhhh.....",
    "....hssssssh....",
    "....swsswss....",
    "....ssrrss......",
    ".....srrrr......",
    "....bbbbbbbk....",
    "...bybbbbbk.....",
    "..bbybbbb.......",
    "....bbbb........",
    "....b..b........",
    "...kk..kk.......",
    "................",
    "................"
  ],
  戦士: [
    "................",
    ".....mmmmmm.....",
    "....mkkkkkkm....",
    "....mssssssm....",
    "....swswwss.....",
    "....ssssss......",
    "...rrrrrrrr.....",
    "..rmmmmmmrkk....",
    "..rmmmmmmrk.....",
    "...rrrrrr.......",
    "....bbbb........",
    "...bb..bb.......",
    "...kk..kk.......",
    "................",
    "................",
    "................"
  ],
  僧侶: [
    "................",
    "......wwww......",
    ".....wwyyww.....",
    ".....wssssw.....",
    ".....swswss.....",
    ".....ssssss.....",
    "....wwwpwww.....",
    "...wwwwpwww.....",
    "...wwwppwww.....",
    "....wwpww.......",
    "....bb.bb.......",
    "...kk..kk.......",
    "................",
    "................",
    "................",
    "................"
  ],
  魔法使い: [
    "................",
    ".......p........",
    "......ppp.......",
    ".....ppppp......",
    "....ppppppp.....",
    "......hhhh......",
    ".....swswss.....",
    ".....ssssss.....",
    "....ppppppp.....",
    "...ppppppppp....",
    "....pppppp......",
    "....bb..bb......",
    "...kk....kk.....",
    "................",
    "................",
    "................"
  ],
  盗賊: [
    "................",
    ".....kkkkkk.....",
    "....kggggggk....",
    "....gssssssg....",
    "....swswss......",
    "....ssssss......",
    "...gggggggg.....",
    "..ggrgggggkk....",
    "...gggggg.......",
    "....gggg........",
    "...bb..bb.......",
    "..kk....kk......",
    "................",
    "................",
    "................",
    "................"
  ],
  騎士: [
    "................",
    ".....wwwwww.....",
    "....wmmmmmmw....",
    "....mssssssm....",
    "....swswwss.....",
    "....ssssss......",
    "...wwwwwwww.....",
    "..wwwwwwwwkk....",
    "...wwwwww.......",
    "....wwww........",
    "...bb..bb.......",
    "..kk....kk......",
    "................",
    "................",
    "................",
    "................"
  ],
  スライム: [
    "................",
    "................",
    ".......a........",
    "......aaa.......",
    ".....aaaaa......",
    "....aaaaaaa.....",
    "...aaaaaaaaa....",
    "..aaacaaacaa....",
    "..aaaaaaaaaa....",
    "..aaaaaddaaa....",
    "...aaaaaaaa.....",
    "....bbbbbb......",
    "................",
    "................",
    "................",
    "................"
  ],
  こうもり: [
    "................",
    "................",
    "...m......m.....",
    "..mmm....mmm....",
    ".mmmmm..mmmmm...",
    "mmmmmmmmmmmmmm..",
    "...mmffffmm.....",
    "....fcffc.......",
    "....fffff.......",
    ".....ddf........",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................"
  ],
  ゴブリン: [
    "................",
    ".....a....a.....",
    "....aaaaaaaa....",
    "....acaaaca.....",
    "....aaaaaaa.....",
    ".....addda......",
    "...mmmmmmmm.....",
    "..mmymmmmmmk....",
    "....mmmmmm......",
    ".....m..m.......",
    "....kk..kk......",
    "................",
    "................",
    "................",
    "................",
    "................"
  ],
  まどうし: [
    "................",
    ".......f........",
    "......fff.......",
    ".....fffff......",
    "....fffffff.....",
    "......mmmm......",
    ".....mcfcmm.....",
    ".....mmmmm......",
    "....ffffffff....",
    "...ffffyffff....",
    "....fffff.......",
    "....m..m........",
    "...kk..kk.......",
    "................",
    "................",
    "................"
  ],
  塔の番人: [
    "................",
    "....m....m......",
    "...mmmmmmmm.....",
    "..mmmyyyymm.....",
    "..mycmmycym.....",
    "..myyyyyyym.....",
    "...mddddm.......",
    "..mmmmmmmm......",
    ".mmmmmmmmmm.....",
    "...mmmmmm.......",
    "..mm....mm......",
    ".kk......kk.....",
    "................",
    "................",
    "................",
    "................"
  ],
  天塔竜: [
    ".......d........",
    "......ddd.......",
    ".....ddddd......",
    "...dddyyddd.....",
    "..ddycyycdd.....",
    "..ddyyyyddd.....",
    "...ddddd........",
    "..mmmmmmmm......",
    ".mmmmmmmmmm.....",
    "mmmmmmmmmmmm....",
    "...mm..mm.......",
    "..kk....kk......",
    "................",
    "................",
    "................",
    "................"
  ]
};

Object.assign(spritePatterns, {
  影狼: [
    "................",
    "..m......m......",
    ".mmm....mmm.....",
    ".mmmmmmmmmm.....",
    "mmmfmmmfmmm.....",
    "mmmmmmmmmmm.....",
    "..mmmdddmm......",
    "...mmmmmm.......",
    "..mmmmmmmm......",
    ".mmm.mmmm.m.....",
    "mm...mm...mm....",
    "k....kk....k....",
    "................",
    "................",
    "................",
    "................"
  ],
  黒騎士: [
    "................",
    ".....mmmmmm.....",
    "....mkkkkkkm....",
    "...mmmyyyymmm...",
    "...mkmccmckm....",
    "...mmyyyyymm....",
    "....mddddm......",
    "...mmmmmmmmk....",
    "..mmmmmmmmmk....",
    ".kmmmmmmmmk.....",
    "...mmmmmm.......",
    "...mm..mm.......",
    "..kk....kk......",
    "................",
    "................",
    "................"
  ],
  闇司祭: [
    "................",
    ".......f........",
    "......fff.......",
    ".....fffff......",
    "....ffmmmff.....",
    "....fmcccmf.....",
    "....fmmmmm......",
    "...ffffffff.....",
    "..ffffyffffk....",
    "...fffffffk.....",
    "....fffff.......",
    "....m..m........",
    "...kk..kk.......",
    "................",
    "................",
    "................"
  ]
});

Object.assign(spritePatterns, {
  勇者: [
    "........................",
    "..........yyyy..........",
    ".........yyyyyy.........",
    "........yyywwyyy........",
    ".......yyhhhhhhyy.......",
    ".......yhhhhhhhhy.......",
    "......hhsssssshh........",
    "......hsswsswssh........",
    "......hssssssssh........",
    ".......ssrrrrss.........",
    "........srrrrs..........",
    "......bbbbbbbbbb........",
    ".....bbybbbbbybb........",
    "....bbbybbbbbybbb.......",
    "....bbbyyyyyybbb........",
    ".....bbbbbbbbbb.........",
    "......bb....bb..........",
    "......bb....bb..........",
    ".....kkk....kkk.........",
    "....kkkk....kkkk........",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  戦士: [
    "........................",
    "........mmmmmmmm........",
    ".......mmkkkkkkmm.......",
    "......mmkkkkkkkkmm......",
    "......mmssssssssmm......",
    "......msswsswwssm.......",
    "......msssssssssm.......",
    ".......sssrrrrss........",
    "......rrrrrrrrrrrr......",
    ".....rrmmmmmmmmrrk......",
    "....rrmmmmmmmmmmrk......",
    "...kkkmmmmmmmmmmrk......",
    ".....rrmmmmmmmmrr.......",
    "......rrrrrrrrrr........",
    ".......bbbbbbbb.........",
    "......bbb....bbb........",
    "......bb......bb........",
    ".....kkk......kkk.......",
    "....kkkk......kkkk......",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  僧侶: [
    "........................",
    ".........wwwwww.........",
    "........wwyyyyww........",
    ".......wwwyyyywww.......",
    ".......wwssssssww.......",
    ".......wsswsswssw.......",
    ".......wssssssssw.......",
    "........sssllss.........",
    ".......wwwwpwwww........",
    "......wwwwwpwwwww.......",
    ".....wwwwpppwwwww.......",
    ".....wwwppwppwwww.......",
    "......wwwpppwwww........",
    ".......wwwpwwww.........",
    "........wwwwww..........",
    "........bb..bb..........",
    ".......bbb..bbb.........",
    "......kkk....kkk........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  魔法使い: [
    "........................",
    "...........p............",
    "..........ppp...........",
    ".........ppppp..........",
    "........ppppppp.........",
    ".......ppppppppp........",
    "......pppccccppp........",
    "........hhhhhh..........",
    ".......hssssssh.........",
    ".......sswsswss.........",
    ".......ssssssss.........",
    "......pppppppppp........",
    ".....pppppppppppp.......",
    "....ppppppyypppp........",
    "....pppppppppppp........",
    "......pppppppp..........",
    ".......bb....bb.........",
    "......kkk....kkk........",
    ".....kkkk....kkkk.......",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  盗賊: [
    "........................",
    "........kkkkkkkk........",
    ".......kkggggggkk.......",
    "......kkggggggggkk......",
    "......kgssssssssgk......",
    "......gsswsswssg........",
    "......gsssssssg.........",
    ".......sssrrss..........",
    "......gggggggggg........",
    ".....ggggngggggkk.......",
    "....ggggnnggggkk........",
    "...kkgggnggggg..........",
    ".....gggggggg...........",
    "......gggggg............",
    ".......bb..bb...........",
    "......bbb..bbb..........",
    ".....kkk....kkk.........",
    "....kkkk....kkkk........",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ],
  騎士: [
    "........................",
    ".........wwwwww.........",
    "........wwmmmmww........",
    ".......wwmmmmmmww.......",
    ".......wmssssssmw.......",
    ".......msswsswwsm.......",
    ".......msssssssm........",
    "........sssrrss.........",
    "......wwwwwwwwww........",
    ".....wwwwwwwwwwwwk......",
    "....wwwwwwwwwwwwwk......",
    "...kkwwwwwwwwwwwwk......",
    ".....wwwwwwwwwwww.......",
    "......wwwwwwwwww........",
    ".......bb....bb.........",
    "......bbb....bbb........",
    ".....kkk......kkk.......",
    "....kkkk......kkkk......",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................"
  ]
});
